services:
  benson_gpt:
    build: .
    volumes:
    - ./src:/workspace/benson_bot/src
    - ./test:/workspace/benson_bot/test
    - ./discord_token.txt:/workspace/benson_bot/discord_token.txt
    - /dev/shm:/dev/shm
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    command: ["python3","-u","/workspace/benson_bot/src/main.py"]